config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "home#index"

  resources :people
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/person.rb
class Person < ApplicationRecord
  has_one_attached :photo

  validates :name, presence: true
  validates :date_of_passing, presence: true
  validates :about, presence: true, length: { minimum: 10 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @people = Person.all.order(:date_of_passing)
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  http_basic_authenticate_with name: Rails.application.credentials.basic[:username], password: Rails.application.credentials.basic[:password], except: [ :index, :show ]

  def index
    redirect_to root_url, status: :moved_permanently
  end
  def show
    @person = Person.find(params[:id])
  end

  def new
    @person = Person.new
  end

  def create
    @person = Person.new(person_params)

    if params[:photo].present?
      @person.photo.attach(params[:photo])
    end

    if @person.save
      redirect_to @person
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @person = Person.find(params[:id])
  end

  def update
    @person = Person.find(params[:id])

    if params[:photo].present?
      @person.photo.purge if @person.photo.attached?
      @person.photo.attach(params[:photo])
    end

    if @person.update(person_params)
      redirect_to @person
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @person = Person.find(params[:id])

    if @person.photo.attached?
      @person.photo.purge
    end

    @person.destroy

    redirect_to root_url, status: :see_other
  end

  private def person_params
    params.require(:person).permit(:name, :date_of_passing, :byline, :about, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/home/index.html.erb
<h1 class="display-1 text-center mt-5">Tombstones</h1>
<p class="lead text-center mb-5">A moment of silence for those that have meant something to me</p>

<div id="people">
    <div class="row mt-4">
    <% @people.each do |person| %>
        <div class="col-md-6 col-xl-4 col-12">
            <div class="card text-center border-0">
                <div class="card-body">
                    <h2 class="card-title"><%= person.name %></h2>
                    <p class="text-secondary"><%= person.byline %></p>
                    <h6 class="card-subtitle mb-2 text-body-secondary"><%= Date::MONTHNAMES[person.date_of_passing.month] %> <%= person.date_of_passing.year %></h6>
                    <%= link_to "", person, class: "stretched-link" %>
                </div>
            </div>
        </div>
    <% end %>
    </div>
</div>

<div class="row mt-md-3 mb-md-3">
    <div class="col col-md-6 offset-md-3 text-center">
        <% if @people.any? %>
            <hr/>
        <% end %>
        <%= link_to "New",
         new_person_url,
         class: "link-primary link-underline-opacity-25 link-underline-opacity-75-hover link-offset-2 link-opacity-50 link-opacity-100-hover",
         data: { turbo_prefetch: :false } %>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Tombstones" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/people/_form.html.erb
<div class="row">
    <div class="col">
        <% if person.errors.any?  %>
            <div class="alert alert-danger">
                <h4>Errors</h4>
                <ul>
                    <% person.errors.each do |error| %>
                        <li><%= error.full_message %></li>
                    <% end %>
                </ul>
            </div>
        <% end %>
    </div>
</div>
<div class="row">
    <div class="col">
        <%= form_with model: person do |form| %>
            <div class="mb-3">
                <%= form.label :name, class: "form-label" %>
                <%= form.text_field :name, class: "form-control" %>
            </div>

            <div class="mb-3">
                <%= form.label :byline, class: "form-label" %>
                <%= form.text_field :byline, class: "form-control" %>
            </div>

            <div class="mb-5">
                <%= form.label :date_of_passing, class: "form-label" %>
                <%= form.date_field :date_of_passing, class: "form-control" %>
            </div>

            <div class="mb-3">
                <%= form.label :about, class: "form-label" %>
                <%= form.text_area :about, class: "form-control", rows: 10 %>
            </div>

            <div class="mb-3">
                <%= form.label :photo, class: "form-label" %>
                <%= form.file_field :photo, class: "form-control" %>
            </div>

            <div>
                <%= form.submit "Save", class: "btn btn-primary" %>
            </div>
        <% end %>
    </div>
</div>

app/views/people/edit.html.erb
<div class="row mt-5">
    <div class="col-12 col-md-6 offset-md-3">
        <div class="row mb-3">
            <div class="col">
                <h1>Edit</h1>
            </div>
        </div>
        <%= render "form", person: @person%>
    </div>
</div>

<div class="row mt-2 mb-2 mt-md-3 mb-md-3">
    <div class="col col-md-6 offset-md-3">
        <hr/>
        <%= link_to "Destroy", person_url(@person), class: "link-danger link-underline-opacity-25 link-underline-opacity-75-hover link-offset-2 link-opacity-50 link-opacity-100-hover", data: {
                            turbo_method: :delete,
                            turbo_confirm: "Are you sure to delete?",
                            turbo_prefetch: :false
                        }%>
    </div>
</div>

app/views/people/new.html.erb
<div class="row mt-5">
    <div class="col-12 col-md-6 offset-md-3">
        <div class="row mb-3">
            <div class="col">
                <h1>New</h1>
            </div>
        </div>
        <%= render "form", person: @person%>
    </div>
</div>

app/views/people/show.html.erb
<div class="row mt-5">
    <% if @person.photo.attached? %>
        <div class="col-12 col-md-6">
            <%= image_tag @person.photo, class: "img-fluid rounded" %>
        </div>
    <% end %>
    <div class="<%= @person.photo.attached? ? 'col' : 'col-6 offset-3' %> text-start">
        <div class="mb-2">
            <%= link_to "Back", root_url, class: "link-secondary link-underline-opacity-25 link-underline-opacity-75-hover link-offset-2 link-opacity-50 link-opacity-100-hover" %>
        </div>
        <h1 class="mb-2 display-2"><%= @person.name %></h1>
        <div>
            <h3 class="text-secondary mb-2"><%= @person.byline %></h3>
            <h6>Passed away on <%= @person.date_of_passing %></h6>
        </div>
        <hr/>
        <p class="text-start">
            <%= simple_format(@person.about) %>
        </p>
        <hr/>
        <%= link_to "Edit",
            edit_person_url,
            class: "link-primary link-underline-opacity-25 link-underline-opacity-75-hover link-offset-2 link-opacity-50 link-opacity-100-hover",
            data: { turbo_prefetch: :false } %>
    </div>
</div>